name = "Idle Engineers CBT"
uid = "199b9a90-ce8e-11ee-a2f8-0800200c9a66"
version = 2
copyright = "camelCase"
description = "Highlight working/Idle T1,T2,T3 Engineers and more on the main map with different overlay for each - improved by ZeRen and Giebmasse. CheeseBerryTweaks v1"
author = "camelCase, ZeRen, Giebmasse, CheeseBerry"
url = "https://github.com/ChessBerry/idleEngineers"
icon = "/mods/idleengineersCBT/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = { }
before = {}
after = {}
